//
//  DummyHeroes.swift
//  MyHero
//
//  Created by M. Abdul Latief -Mz on 08/04/21.
//

import UIKit

let heroes = [
  Hero(id: 1, photo: "ahmad_dahlan", name: "Ahmad Dahlan", description: "Kiai Haji Ahmad Dahlan atau Muhammad Darwis (bahasa Arab: أحمد دحلان‎; lahir di Yogyakarta, 1 Agustus 1868 – meninggal di Yogyakarta, 23 Februari 1923 pada umur 54 tahun) adalah seorang Pahlawan Nasional Indonesia yang merupakan pendiri Muhammadiyah. Dia adalah putra keempat dari tujuh bersaudara dari keluarga K.H. Abu Bakar. KH Abu Bakar adalah seorang ulama dan khatib terkemuka di Masjid Besar Kasultanan Yogyakarta pada masa itu, dan ibu dari K.H. Ahmad Dahlan adalah puteri dari H. Ibrahim yang juga menjabat penghulu Kesultanan Ngayogyakarta Hadiningrat pada masa itu."),
  Hero(id: 2, photo: "ahmad_yani", name: "Ahmad Yani", description: "Jenderal TNI Anumerta Ahmad Yani (juga dieja Achmad Yani; lahir di Purworejo, Jawa Tengah, 19 Juni 1922 – meninggal di Lubang Buaya, Jakarta, 1 Oktober 1965 pada umur 43 tahun) adalah komandan Tentara Nasional Indonesia Angkatan Darat, dan dibunuh oleh anggota Gerakan 30 September saat mencoba untuk menculik dia dari rumahnya."),
  Hero(id: 3, photo: "bung_tomo", name: "Bung Tomo", description: "Sutomo (lahir di Surabaya, Jawa Timur, 3 Oktober 1920 – meninggal di Padang Arafah, Arab Saudi, 7 Oktober 1981 pada umur 61 tahun)[1] lebih dikenal dengan sapaan akrab oleh rakyat sebagai Bung Tomo, adalah pahlawan yang terkenal karena peranannya dalam membangkitkan semangat rakyat untuk melawan kembalinya penjajah Belanda melalui tentara NICA, yang berakhir dengan pertempuran 10 November 1945 yang hingga kini diperingati sebagai Hari Pahlawan."),
  Hero(id: 4, photo: "gatot_subroto", name: "Gatot Subroto", description: "Jenderal TNI (Purn.) Gatot Soebroto (lahir di Sumpiuh, Banyumas, Jawa Tengah, 10 Oktober 1907 – meninggal di Jakarta, 11 Juni 1962 pada umur 54 tahun) adalah tokoh perjuangan militer Indonesia dalam merebut kemerdekaan dan juga pahlawan nasional Indonesia. Ia dimakamkan di Ungaran, kabupaten Semarang."),
  Hero(id: 5, photo: "ki_hadjar_dewantara", name: "Ki Hadjar Dewantara", description: "Raden Mas Soewardi Soerjaningrat (EBI: Suwardi Suryaningrat, sejak 1922 menjadi Ki Hadjar Dewantara, EBI: Ki Hajar Dewantara, beberapa menuliskan bunyi bahasa Jawanya dengan Ki Hajar Dewantoro; lahir di Pakualaman, 2 Mei 1889 – meninggal di Yogyakarta, 26 April 1959 pada umur 69 tahun, selanjutnya disingkat sebagai Soewardi atau KHD) adalah aktivis pergerakan kemerdekaan Indonesia, kolumnis, politisi, dan pelopor pendidikan bagi kaum pribumi Indonesia dari zaman penjajahan Belanda. Ia adalah pendiri Perguruan Taman Siswa, suatu lembaga pendidikan yang memberikan kesempatan bagi para pribumi untuk bisa memperoleh hak pendidikan seperti halnya para priyayi maupun orang-orang Belanda.Tanggal kelahirannya sekarang diperingati di Indonesia sebagai Hari Pendidikan Nasional. Bagian dari semboyan ciptaannya, tut wuri handayani, menjadi slogan Kementerian Pendidikan Nasional Indonesia. Namanya diabadikan sebagai salah sebuah nama kapal perang Indonesia, KRI Ki Hajar Dewantara. Potret dirinya diabadikan pada uang kertas pecahan 20.000 rupiah tahun edisi 1998. Ia dikukuhkan sebagai pahlawan nasional yang ke-2 oleh Presiden RI, Sukarno, pada 28 November 1959 (Surat Keputusan Presiden Republik Indonesia No. 305 Tahun 1959, tanggal 28 November 1959)."),
  Hero(id: 6, photo: "mohammad_hatta", name: "Mohammad Hatta", description: "Dr. (H.C.) Drs. H. Mohammad Hatta (populer sebagai Bung Hatta; lahir dengan nama Mohammad Athar di Fort de Kock, Hindia Belanda, 12 Agustus 1902 – meninggal di Jakarta, 14 Maret 1980 pada umur 77 tahun) adalah negarawan dan ekonom Indonesia yang menjabat sebagai Wakil Presiden Indonesia pertama. Ia bersama Soekarno memainkan peranan sentral dalam perjuangan kemerdekaan Indonesia dari penjajahan Belanda sekaligus memproklamirkannya pada 17 Agustus 1945. Ia pernah menjabat sebagai Perdana Menteri dalam Kabinet Hatta I, Hatta II, dan RIS. Pada 1956, ia mundur dari jabatan wakil presiden karena berselisih dengan Presiden Soekarno. Hatta dikenal akan komitmennya pada demokrasi. Ia mengeluarkan Maklumat X yang menjadi tonggak awal demokrasi Indonesia. Di bidang ekonomi, pemikiran dan sumbangsihnya terhadap perkembangan koperasi membuat ia dijuluki sebagai Bapak Koperasi. Hatta meninggal pada 1980 dan jenazahnya dimakamkan di Tanah Kusir, Jakarta. Pemerintah Indonesia menetapkannya sebagai salah seorang Pahlawan Nasional Indonesia pada tanggal 23 Oktober 1986 melalui Keppres nomor 081/TK/1986. Namanya bersanding dengan Soekarno sebagai Dwi-Tunggal dan disematkan pada Bandar Udara Soekarno-Hatta. Di Belanda, namanya diabadikan sebagai nama jalan di kawasan perumahan Zuiderpolder, Haarlem."),
  Hero(id: 7, photo: "sudirman", name: "Soedirman", description: "Jenderal Besar TNI (Anumerta) Raden Soedirman (EYD: Sudirman; lahir di Purbalingga, 24 Januari 1916 – meninggal di Magelang, 29 Januari 1950 pada umur 34 tahun[a]) adalah seorang perwira tinggi Indonesia pada masa Revolusi Nasional Indonesia. Sebagai panglima besar Tentara Nasional Indonesia pertama, ia adalah sosok yang dihormati di Indonesia. Terlahir dari pasangan rakyat biasa di Purbalingga, Hindia Belanda, Soedirman diadopsi oleh pamannya yang seorang priyayi. Setelah keluarganya pindah ke Cilacap pada tahun 1916, Soedirman tumbuh menjadi seorang siswa rajin; ia sangat aktif dalam kegiatan ekstrakurikuler, termasuk mengikuti program kepanduan yang dijalankan oleh organisasi Islam Muhammadiyah. Saat di sekolah menengah, Soedirman mulai menunjukkan kemampuannya dalam memimpin dan berorganisasi, dan dihormati oleh masyarakat karena ketaatannya pada Islam. Setelah berhenti kuliah keguruan, pada 1936 ia mulai bekerja sebagai seorang guru, dan kemudian menjadi kepala sekolah, di sekolah dasar Muhammadiyah; ia juga aktif dalam kegiatan Muhammadiyah lainnya dan menjadi pemimpin Kelompok Pemuda Muhammadiyah pada tahun 1937. Setelah Jepang menduduki Hindia Belanda pada 1942, Soedirman tetap mengajar. Pada tahun 1944, ia bergabung dengan tentara Pembela Tanah Air (PETA) yang disponsori Jepang, menjabat sebagai komandan batalion di Banyumas. Selama menjabat, Soedirman bersama rekannya sesama prajurit melakukan pemberontakan, hingga kemudian diasingkan ke Bogor."),
  Hero(id: 8, photo: "sukarno", name: "Soekarno", description: "Dr. (H.C.) Ir. H. Soekarno1 (ER, EYD: Sukarno, nama lahir: Koesno Sosrodihardjo) (lahir di Surabaya, Jawa Timur, 6 Juni 1901 – meninggal di Jakarta, 21 Juni 1970 pada umur 69 tahun) adalah Presiden pertama Republik Indonesia yang menjabat pada periode 1945–1967. Ia adalah seorang tokoh perjuangan yang memainkan peranan penting dalam memerdekakan bangsa Indonesia dari penjajahan Belanda. Ia adalah Proklamator Kemerdekaan Indonesia (bersama dengan Mohammad Hatta) yang terjadi pada tanggal 17 Agustus 1945. Soekarno adalah yang pertama kali mencetuskan konsep mengenai Pancasila sebagai dasar negara Indonesia dan ia sendiri yang menamainya. Soekarno menandatangani Surat Perintah 11 Maret 1966 (Supersemar) yang kontroversial, yang isinya —berdasarkan versi yang dikeluarkan Markas Besar Angkatan Darat— menugaskan Letnan Jenderal Soeharto untuk mengamankan dan menjaga keamanan negara dan institusi kepresidenan. Supersemar menjadi dasar Letnan Jenderal Soeharto untuk membubarkan Partai Komunis Indonesia (PKI) dan mengganti anggota-anggotanya yang duduk di parlemen. Setelah pertanggungjawabannya ditolak Majelis Permusyawaratan Rakyat Sementara (MPRS) pada sidang umum ke empat tahun 1967, Soekarno diberhentikan dari jabatannya sebagai presiden pada Sidang Istimewa MPRS pada tahun yang sama dan Soeharto menggantikannya sebagai pejabat Presiden Republik Indonesia."),
  Hero(id: 9, photo: "supomo", name: "Supomo", description: "Marsekal Muda TNI (Purn.) Supomo, S.I.P., M.Sc. (lahir di Kota Raha, Sulawesi Tenggara, 7 Februari 1959; umur 62 tahun) adalah seorang purnawirawan perwira tinggi TNI Angkatan Udara dan tokoh militer Indonesia lulusan Akademi Angkatan Udara (AAU) tahun 1983. Lebih dari tiga puluh tahun berkarya, memiliki spesialisasi di bidang pengamanan dan intelijen, hubungan internasinoal, politik, dan pembangunan ekonomi. Kini aktif menjabat sebagai Staf Khusus Kasau. Jabatan terakhir jenderal bintang dua ini adalah Wakil Kepala Bais TNI, Waaspam KASAU, dan Bandep Lingstranas Dejiandra Setjen Dewan Ketahanan Nasional."),
  Hero(id: 10, photo: "Mz", name: "M. Abdul Latief -Mz", description: "Muhammad Abdul Latief merupakan pahlawan negara tempest dengan membantu rimuru mengalahkan kekaisaran timur dengan keberaniannya Tue Dragon Lord Veldanava pun di pukul mundur olehnya, sehingga menyebabkan entitas manusianya berubah menjadi dewa di Universe Tensura")
]

